### ISSUE TITLE
RapidSVN fails to compile

### ISSUE THREAD

**Issue by Xylemon** [Ponce/slackbuilds#12] opened 2016-01-04 08:47 UTC
RapidSVN fails to compile on current with this error:

```
client_ls.cpp:69:49: error: 'svn_sort__hash' was not declared in this scope
               hash, compare_items_as_paths, pool);
                                                 ^
In file included from /usr/include/subversion-1/svn_client.h:37:0,
                 from client_ls.cpp:29:
/usr/include/apr-1/apr_tables.h:141:59: error: invalid use of incomplete type 'struct svn_sort__item_t'
 #define APR_ARRAY_IDX(ary,i,type) (((type *)(ary)->elts)[i])
                                                           ^
client_ls.cpp:79:15: note: in expansion of macro 'APR_ARRAY_IDX'
       item = &APR_ARRAY_IDX(array, i, svn_sort__item_t);
               ^
In file included from client_ls.cpp:31:0:
/usr/include/subversion-1/svn_sorts.h:55:16: note: forward declaration of 'struct svn_sort__item_t'
 typedef struct svn_sort__item_t svn_sort__item_t;
                ^
client_ls.cpp:81:49: error: invalid use of incomplete type 'svn_sort__item_t {aka struct svn_sort__item_t}'
       entryname = static_cast<const char *>(item->key);
                                                 ^
In file included from client_ls.cpp:31:0:
/usr/include/subversion-1/svn_sorts.h:55:16: note: forward declaration of 'svn_sort__item_t {aka struct svn_sort__item_t}'
 typedef struct svn_sort__item_t svn_sort__item_t;
                ^
client_ls.cpp:84:51: error: invalid use of incomplete type 'svn_sort__item_t {aka struct svn_sort__item_t}'
                (apr_hash_get(hash, entryname, item->klen));
                                                   ^
In file included from client_ls.cpp:31:0:
/usr/include/subversion-1/svn_sorts.h:55:16: note: forward declaration of 'svn_sort__item_t {aka struct svn_sort__item_t}'
 typedef struct svn_sort__item_t svn_sort__item_t;
                ^
Makefile:388: recipe for target 'client_ls.lo' failed
make[2]: *** [client_ls.lo] Error 1
make[2]: Leaving directory '/tmp/SBo/rapidsvn-0.12.1/src/svncpp'
Makefile:576: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/rapidsvn-0.12.1/src'
Makefile:299: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Not sure when this started happening, but I know it's been failing for a while now. Any fix is greatly appreciated.

**Comment by Ponce** [comment] 2016-01-04 16:43
I had a look but ATM I have no idea how to make it build: it looks like it's mainly unmaintained upstream since years.
try contacting the rapidsvn.SlackBuild's maintainer.

**Comment by idlemoor** [comment] 2016-01-04 18:03
This is the same problem as Gentoo bug 558572 https://bugs.gentoo.org/show_bug.cgi?id=558572 ... the problem is that RapidSVN was using a private Subversion API which became hidden in subversion-1.9. You could try raising an issue with RapidSVN upstream at https://github.com/RapidSVN/RapidSVN, or if you are very brave you could look at some of the patches other packages applied for the same problem e.g. http://lists.opensuse.org/archive/opensuse-commit/2015-08/msg01185.html

**Comment by Xylemon** [comment] 2016-01-04 18:13
Thanks, I'll take a look at the patches.

**Comment by willysr** [comment] 2016-01-05 00:39
Fixed in current-wip branch
http://slackbuilds.org/cgit/slackbuilds/commit/?h=current-wip&id=c2df77021b476ca9484772361003df04fa03038a

**Comment by idlemoor** [comment] 2016-01-05 01:13
We should nominate Willy for "person of the year 2016" right now :D
Should we send the new patch to Gentoo? :D :D :D

**Comment by willysr** [comment] 2016-01-05 01:17
They already have it, but on different bug report, but i think it's not yet merged

**Comment by Ponce** [comment] 2016-01-05 11:35
applied the same commit to a dedicated rapidsvn branch, thanks Willy!

**Closed by Ponce** 2016-01-05 11:35 UTC

**Comment by Xylemon** [comment] 2016-01-05 14:44
Thanks a bunch @willysr!
