### ISSUE TITLE
nvidia-driver - ldconfig warns about GL symlinks

### ISSUE THREAD

**Issue by edrozenberg** [Ponce/slackbuilds#60] opened 2019-11-03 03:42 UTC
Currently running latest slackware64 -current, and installed nvidia-kernel and nvidia-driver packages using ponce slackbuilds:

nvidia-driver-430.50-x86_64-1_SBo
nvidia-kernel-430.50_4.19.81-x86_64-1_SBo

When I run `ldconfig`, I get the following output:

```
ldconfig: /usr/lib64/libGLdispatch.so.0 is not a symbolic link
ldconfig: /usr/lib64/libGLX.so.0 is not a symbolic link
ldconfig: /usr/lib64/libOpenGL.so.0 is not a symbolic link
```

Seems like it's a conflict between the files installed by the Slackware `libglvnd` package, and the nvidia-driver package.  I'm guessing  `nvidia-switch` might need some changes but not sure of the best approach - overwrite the files installed by `libglvnd`?

Details about the files mentioned in the ldconfig warnings:

```
# ls -al /usr/lib64/libGLdispatch.so*
lrwxrwxrwx 1 root root   22 Nov  2 20:20 /usr/lib64/libGLdispatch.so -> libGLdispatch.so.0.0.0
-rwxr-xr-x 1 root root 716K Nov  2 20:22 /usr/lib64/libGLdispatch.so.0
-rwxr-xr-x 1 root root 627K Oct 29 12:09 /usr/lib64/libGLdispatch.so.0.0.0
```
```
# grep libGLdispatch.so /var/log/packages/*
/var/log/packages/libglvnd-1.2.0-x86_64-4:usr/lib64/libGLdispatch.so.0.0.0
/var/log/packages/nvidia-driver-430.50-x86_64-1_SBo:usr/lib64/libGLdispatch.so.0
```

```
# ls -al /usr/lib64/libGLX.so*
lrwxrwxrwx 1 root root  11 Nov  2 20:26 /usr/lib64/libGLX.so -> libGLX.so.0
-rwxr-xr-x 1 root root 64K Nov  2 20:22 /usr/lib64/libGLX.so.0
-rwxr-xr-x 1 root root 71K Oct 29 12:09 /usr/lib64/libGLX.so.0.0.0
```
```
# grep libGLX.so.0 /var/log/packages/*
/var/log/packages/libglvnd-1.2.0-x86_64-4:usr/lib64/libGLX.so.0.0.0
/var/log/packages/nvidia-driver-430.50-x86_64-1_SBo:usr/lib64/libGLX.so.0
```

```
# ls -al /usr/lib64/libOpenGL.so*
lrwxrwxrwx 1 root root   14 Nov  2 20:26 /usr/lib64/libOpenGL.so -> libOpenGL.so.0
-rwxr-xr-x 1 root root 211K Nov  2 20:22 /usr/lib64/libOpenGL.so.0
-rwxr-xr-x 1 root root 195K Oct 29 12:09 /usr/lib64/libOpenGL.so.0.0.0
```
```
# grep libOpenGL.so /var/log/packages/*
/var/log/packages/libglvnd-1.2.0-x86_64-4:usr/lib64/libOpenGL.so.0.0.0
/var/log/packages/nvidia-driver-430.50-x86_64-1_SBo:usr/lib64/libOpenGL.so.0
```

**Comment by lockywolf** [comment] 2019-11-03 05:14
Confirmed

**Comment by Ponce** [comment] 2019-11-03 22:16
I got those warnings too and they seem harmless: BTW, patches that silence them are welcome.

**Comment by edrozenberg** [comment] 2019-11-20 22:10
> I got those warnings too and they seem harmless: BTW, patches that will silence them are welcome.

It doesn't look totally unimportant because one or more of those .so symlinks point to the libraries installed by `libglvnd` rather than the versions installed by `nvidia-driver`. Maybe it doesn't make a functional difference, not sure.

I applied the following "hack" below after installing the latest `nvidia-driver` package:
```
mkdir -p /var/log/nvidia/64/

mv /usr/lib64/libGLdispatch.so.0.0.0 /var/log/nvidia/64/
mv /usr/lib64/libGLdispatch.so.0 /usr/lib64/libGLdispatch.so.0.0.0
rm -f /usr/lib64/libGLdispatch.so
ln -s /usr/lib64/libGLdispatch.so.0 /usr/lib64/libGLdispatch.so
ln -s /usr/lib64/libGLdispatch.so.0.0.0 /usr/lib64/libGLdispatch.so.0

mv /usr/lib64/libGLX.so.0.0.0 /var/log/nvidia/64/
mv /usr/lib64/libGLX.so.0 /usr/lib64/libGLX.so.0.0.0
ln -s /usr/lib64/libGLX.so.0.0.0 /usr/lib64/libGLX.so.0

mv /usr/lib64/libOpenGL.so.0.0.0 /var/log/nvidia/64/
mv /usr/lib64/libOpenGL.so.0 /usr/lib64/libOpenGL.so.0.0.0
ln -s /usr/lib64/libOpenGL.so.0.0.0 /usr/lib64/libOpenGL.so.0
```

If that looks to be along the correct lines, can submit a patch to `nvidia-switch`. I did notice the current `nvidia-switch` in ponce appears to be a no-op (does not move or replace any GL files like the older one in 14.2 does).

**Comment by Ponce** [comment] 2019-11-21 06:01
the nvidia-switch in SBo just moves the libGL.la files, but *.la files have been removed from current and this created conflicts (compiled stuff linking to the nvidia libGL.la), so I removed the lines that handles that file from the SlackBuild and nvidia-switch.
as things now seems to work ok (I have not seen any functional difference here, do you?), before appling an eventual patch I would like you to get in touch with the script maintainer and ask him if the hack you applied there is actually safe.

**Comment by kingbeowulf** [comment] 2019-11-23 20:03
Like I have said a googleplex times before:
(1) The SBo Nvidia buildscripts scripts are only supported on 14.2. So "not a bug, won't fix" 
(2) like libvdpau previously, libglvnd was open sourced and can be installed separately from the Nvidia binary package - it is now included in current. 
(3) I need to do a complete re-write - again - to account for the now extraneous files in the Nvidia binary. 
I just built a new Ryzen X570 system in a mini-ITX case to test current, but do not have any modern Nvidia or AMD GPUs that fit (the one card that does has the power socket on the end so I can't plug in!). I'll be doing one more Nvidia update for 14.2 to start incorporating the changes. Stay tuned.

**Comment by edrozenberg** [comment] 2020-01-28 23:24
It appears the issues are resolved in the latest nvidia-driver slackbuild version I tried (7.1 15-Dec-2019, driver version 440.44).

One *important* note, when using Slackware -current, a parameter need to be passed to the Slackbuild as follows:

```
CURRENT=yes ./nvidia-driver.SlackBuild
```

Otherwise `CURRENT` defaults to `no`, which causes the `nvidia-driver` package to contain several files (libGLdispatch.*, libGLX.*, libOpenGL.*) which will overwrite the ones provided by the Slackware -current `libglvnd` package causing the bit of a mess described earlier.

To clean up any existing "mess", would suggest:
- Removing any existing older `nvidia-driver` package
- Reinstalling `libglvnd` package: `slackpkg reinstall libglvnd`
- Build the latest `nvidia-driver` package making sure to set `CURRENT` to `yes` for the Slackbuild
- Install the built `nvidia-driver` package
- Run `ldconfig` and make sure there are no errors/warnings

**Closed** 2020-01-29 05:29 UTC

**Comment by jjslegacy** [comment] 2024-01-25 14:55
any updates on this or anyone have a fix that works?
